name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Heroku buildpack
        run: |
          heroku buildpacks:set heroku/python

      - name: Deploy to Heroku
        uses: heroku/deploy-v2@v1
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ipexemail-scraper
          
